name: UberChat
main: net.daboross.bukkitdev.uberchat.UberChat
version: 2.4
author: Dabo Ross
description: Smart Chat Handler
commands:
   colorize:
     description: Toggles colorizing all messages.
     usage: /<command>
     permission: uberchat.colorize
   me:
     description: Describes an action in context of the player.
     usage: /<command> <action>
     permission: uberchat.me
   msg:
     description: Sends a private message to a player.
     usage: /<command> <playername> <message>
     permission: uberchat.msg
     aliases: [m, tell, t]
   reply:
     description: Sends a message to the last person who messaged you
     usage: /<command> <message>
     permission: uberchat.reply
     aliases: [r]
   shout:
     description: Shouts a message
     usage: /<command> <message>
     permission: uberchat.shout
     aliases: [sh, bc]
permissions:
  uberchat.colorize:
    description: Allows you to use /colorize
    default: true
  uberchat.me:
    description: Allows you to use /me
    default: true
  uberchat.msg:
    description: Allows you to use /msg
    default: true
  uberchat.reply:
    description: Allows you to use /r
    default: true
  uberchat.msgspy:
    description: Allows you to spy on private messages
    default: false
  uberchat.shout:
    description: Allows you to use /shout
    default: false