name: UberChat
main: net.daboross.bukkitdev.uberchat.UberChat
version: 2.2
author: Dabo Ross
description: Newlanders's Chat Handler
commands:
   colorme:
     description: Toggles the 'Chat Color' formatting option.
     usage: /<command>
     permission: uberchat.colorize
   toggleme:
     description: Toggles the 'Chat Toggle' formatting option.
     usage: /<command>
     permission: uberchat.toggleme
   color:
     description: Sends a colorized chat message or command.
     usage: /<command> </Command|Message>
     permission: uberchat.colorize
   me:
     description: Describes an action in context of the player.
     usage: /<command> <action>
     permission: uberchat.me
   msg:
     description: Sends a private message to a player.
     usage: /<command> <playername> <message>
     permission: uberchat.msg
     aliases: [m, tell, t]
   reply:
     description: Sends a message to the last person who messaged you
     usage: /<command> <message>
     permission: uberchat.reply
     aliases: [r]
permissions:
  uberchat.colorize:
    description: Allows you to use /color and /colorme
    default: true
  uberchat.toggleme:
    description: Allows you to use /toggleme
    default: true
  uberchat.me:
    description: Allows you to use /me
    default: true
  uberchat.msg:
    description: Allows you to use /msg
    default: true
  uberchat.reply:
    description: Allows you to use /r
    default: true